from __future__ import annotations

LANG = "ru"

_RU: dict[str, str] = {
    "app.title": "Batch Booru Downloader",
    "tab.home": "Главная",
    "tab.config": "Настройки",
    "col.provider": "Сайт",
    "col.auth": "Логин",
    "col.queued": "В очереди",
    "col.links": "Путь до файла с ссылками",
    "col.param": "Параметр",
    "col.value": "Значение",
    "bind.download": "Download",
    "bind.reload_links": "Reload links",
    "bind.auth": "Auth",
    "bind.recheck_auth": "Re-check auth",
    "bind.check_updates": "Check updates",
    "bind.upgrade": "Upgrade pkgs",
    "bind.reboot": "Reboot",
    "bind.home": "Главная",
    "bind.config": "Настройки",
    "bind.quit": "Quit",
    "modal.choice_hint": "← → — выбор · Enter — ок · Esc — отмена",
    "modal.input_hint": "Enter — ок · Esc — отмена",
    "set.pixiv_ugoira": "Pixiv ugoira:",
    "set.danbooru_ttl": "Danbooru cookie TTL (мин)",
    "set.twitter_format": "Twitter (yt-dlp формат)",
    "set.log_level": "Уровень лога",
    "set.request_delay": "Задержка запросов (с)",
    "set.max_retries": "Повторов при ошибке",
    "set.check_updates": "Проверять обновления библиотек",
    "config.help": "Настройки — ↑/↓ выбор, Enter изменить. * = требуется перезапуск. Сохраняется в settings.env.",
    "config.readonly_header": "[dim]Только чтение (редактируйте settings.env; требуется перезапуск.):[/dim]",
    "restart.marker": " *",
    "val.on": "Вкл",
    "val.off": "Выкл",
    "val.default": "(default)",
    "status.auth": "([b]{name}[/b]) Auth: [{color}]{state}[/{color}]",
    "status.auth_message": " [dim]({message})[/dim]",
    "extra.cookie_none": " | Cookies не заданы.",
    "extra.cookie_live": " | Cookies: {mm:02d}:{ss:02d} до истечения (TTL {ttl}м)",
    "extra.cookie_expired": " | Cookies, вероятно, истекли.",
    "extra.ugoira": " | Ugoira: {mode}",
    "extra.twitter": " | yt-dlp: {fmt}",
    "dl.queue_idle": "Очередь: -",
    "dl.ready": "Готов к загрузке",
    "dl.overall": "Скачано: {done} файлов | {mb:.1f} MB",
    "dl.file_progress": "{filename}  {done:.1f}/{total:.1f} MB | {speed:.2f} MB/s",
    "dl.file_progress_nosize": "{filename}  {done:.1f} MB | {speed:.2f} MB/s",
    "dl.size_unknown": " размер неизвестен",
    "log.debug_on": "[dim]DEBUG-логи включены.[/dim]",
    "log.auth_status": "[dim]Auth[/dim] {name}: {state} — {message}",
    "log.need_number": "[red]{label}: нужно число, получено '{value}'[/red]",
    "log.save_failed": "[red]Не удалось сохранить settings.env: {error}[/red]",
    "log.apply_failed": "[yellow]{label}: сохранено, но не применено: {error}[/yellow]",
    "log.restart_hint": " [dim](перезагрузите для применения изменений)[/dim]",
    "log.setting_saved": "[green]{label} → {value}[/green]{hint}",
    "log.checking_auth": "[dim]Проверяю auth...[/dim]",
    "log.reloaded_links": "[b]{name}[/b]: буфер ссылок обновлён → {n} в очереди",
    "log.auth_busy": "[yellow]Идёт загрузка — обновление auth недоступно.[/yellow]",
    "log.auth_no_refresh": "[yellow]{name}: интерактивное обновление auth не поддерживается ({message}).[/yellow]",
    "log.already_downloading": "[yellow]Уже идёт загрузка.[/yellow]",
    "log.start": "[b]Старт[/b]: {name}",
    "log.download_done": "[green]Загрузка завершена.[/green]",
    "log.event_error": "[red]\\[{prefix}] {message}[/red]",
    "log.event_info": "[dim]\\[{prefix}][/dim] {message}",
    "log.checking_updates": "[dim]Проверяю обновления библиотек...[/dim]",
    "log.pkg_error": "[red]{pkg}: {error}[/red]",
    "log.upgrade_busy": "[yellow]Обновление уже идёт...[/yellow]",
    "log.upgrade_start": "[yellow]Обновляю устаревшие пакеты...[/yellow]",
    "log.pkg_check_failed": "[red]{pkg}: проверка не удалась: {error}[/red]",
    "log.pkg_uptodate": "[green]{pkg}: уже актуально ({installed})[/green]",
    "log.pkg_upgrading": "[yellow]{pkg}: обновляю {installed} → {latest}...[/yellow]",
    "log.pkg_pip_failed": "[red]{pkg}: pip не запустился: {error}[/red]",
    "log.pkg_done": "[green]{pkg}: готово[/green] [dim]{tail}[/dim]",
    "log.pkg_pip_code": "[red]{pkg}: pip код {code}[/red] [dim]{tail}[/dim]",
    "log.all_uptodate": "[green]Обновлений нет.[/green]",
    "log.restart_to_apply": "[dim]Перезагрузите для применения обновлений.[/dim]",
    "log.reboot_busy": "[yellow]Идёт загрузка — дождитесь завершения перед перезапуском.[/yellow]",
    "event.auth_check_failed": "Проверка auth не удалась: {error}",
    "event.auth_not_ready": "Auth не готов: {message}.",
    "auth.suspend_title": "  {name}: обновление авторизации",
    "auth.suspend_intro": "Следуйте подсказкам ниже. После завершения интерфейс вернётся.\n",
    "auth.suspend_result": "\nРезультат: {state}",
    "auth.suspend_error": "Ошибка обновления auth: {error}",
    "auth.suspend_return": "\nНажмите Enter для продолжения...",
    "prov.auth_not_required": "Авторизация не требуется",
    "prov.downloading": "Скачивание: {filename}",
    "run.links_file": "Файл ссылок: {path}",
    "run.no_new": "Новых ссылок нет.",
    "run.new_count": "Новых ссылок: {n}",
    "run.resolve_crash": "Критическая ошибка провайдера при разборе ссылки: {error}",
    "run.resolve_failed": "Не удалось разобрать {url}",
    "run.already_had": " (уже загружено)",
    "run.ok": "OK: {filename}{suffix}",
    "run.fail": "FAIL: {filename}: {error}",
    "danbooru.auth_no_creds": "Учётные данные не заданы.",
    "danbooru.auth_no_cookie": "Нет рантайм-cookie Cloudflare.",
    "danbooru.auth_ok": "",
    "danbooru.auth_failed": "Проверка Danbooru не удалась: {error}",
    "danbooru.refresh_title": "\nDanbooru: обновление авторизации",
    "danbooru.refresh_1": "1) Откроется браузер с Danbooru.",
    "danbooru.refresh_2": "2) При необходимости пройдите Cloudflare/вход.",
    "danbooru.refresh_3": "3) Используйте расширение Danbooru Cookie Helper -> Copy cookie.",
    "danbooru.refresh_4": "4) Вставьте cookie ниже. Cookie хранится в ОЗУ только на текущий запуск.\n",
    "danbooru.cookie_prompt": "Вставьте заголовок Danbooru Cookie: ",
    "danbooru.cookie_missing": "Cookie не введён",
    "danbooru.bad_url": "Не удалось извлечь id из Danbooru URL",
    "danbooru.api_error": "Danbooru API недоступен. Ошибка: {error}",
    "danbooru.no_media": "Danbooru post {post_id}: media URL не найден",
    "gelbooru.auth_missing": "Учётные данные не заданы.",
    "gelbooru.auth_ok": "",
    "gelbooru.bad_url": "Не удалось извлечь id из Gelbooru URL",
    "gelbooru.need_creds": "Gelbooru API требует заданные учётные данные в settings.env",
    "gelbooru.api_error": "Gelbooru API недоступен или ключи неверны: {error}",
    "gelbooru.not_found": "Gelbooru post {post_id} не найден",
    "gelbooru.no_media": "Gelbooru post {post_id}: media URL не найден",
    "moebooru.auth_optional": "Авторизация рекомендуется, но не обязательна",
    "moebooru.auth_ok": "",
    "moebooru.auth_incomplete": "{name}: задан USERNAME, но нет PASSWORD_HASH / PASSWORD (или API_KEY)",
    "moebooru.bad_url": "Не удалось извлечь id из {name} URL",
    "moebooru.not_found": "{name} post {post_id} не найден",
    "moebooru.no_media": "{name} post {post_id}: media URL не найден",
    "sankaku.auth_ok": "",
    "sankaku.auth_missing": "Токен недействителен или учётные данные неверны.",
    "sankaku.auth_failed": "Проверка авторизации Sankaku не удалась: {error}",
    "sankaku.bad_url": "Не удалось извлечь Sankaku post id",
    "sankaku.not_found": "Sankaku post {post_id} не найден / API недоступен",
    "sankaku.no_media": "Sankaku post {post_id}: media URL не найден",
    "pixiv.no_gppt": "gppt не установлен. Установи: pip install gppt",
    "pixiv.gppt_no_token": "gppt не вернул refresh_token.",
    "pixiv.no_pixivpy": "pixivpy3 не установлен: pip install pixivpy3",
    "pixiv.empty_token": "Пустой Pixiv refresh_token",
    "pixiv.auth_no_token": "Pixiv refresh_token не задан",
    "pixiv.auth_ok": "",
    "pixiv.auth_failed": "Проверка токена Pixiv не удалась: {error}",
    "pixiv.refresh_title": "\nPixiv: обновление авторизации",
    "pixiv.refresh_intro": "gppt откроет окно браузера. При запросе войдите в Pixiv там.\n",
    "pixiv.gppt_login_failed": "Вход в Pixiv через gppt не удался: {error}",
    "pixiv.token_missing_refresh": "Токен Pixiv отсутствует. Сначала обновите авторизацию Pixiv.",
    "pixiv.bad_url": "Не удалось извлечь Pixiv artwork id",
    "pixiv.not_found": "Pixiv artwork {illust_id} не найден",
    "pixiv.no_media": "Pixiv artwork {illust_id}: media URL не найден",
    "twitter.bad_url": "Не удалось извлечь tweet/status id",
    "twitter.no_ytdlp": "yt-dlp не установлен",
    "twitter.ytdlp_status": "Загрузка через yt-dlp",
}

_EN: dict[str, str] = {
    "app.title": "Batch Booru Downloader",
    "tab.home": "Home",
    "tab.config": "Config",
    "col.provider": "Provider",
    "col.auth": "Auth",
    "col.queued": "Queued",
    "col.links": "Links file",
    "col.param": "Parameter",
    "col.value": "Value",
    "bind.download": "Download",
    "bind.reload_links": "Reload links",
    "bind.auth": "Auth",
    "bind.recheck_auth": "Re-check auth",
    "bind.check_updates": "Check updates",
    "bind.upgrade": "Upgrade pkgs",
    "bind.reboot": "Reboot",
    "bind.home": "Home",
    "bind.config": "Config",
    "bind.quit": "Quit",
    "modal.choice_hint": "← → — select · Enter — ok · Esc — cancel",
    "modal.input_hint": "Enter — ok · Esc — cancel",
    "set.pixiv_ugoira": "Pixiv ugoira: mode",
    "set.danbooru_ttl": "Danbooru cookie TTL (min)",
    "set.twitter_format": "Twitter yt-dlp format",
    "set.log_level": "Log level",
    "set.request_delay": "Request delay (s)",
    "set.max_retries": "Retries on error",
    "set.check_updates": "Check library updates",
    "config.help": "[b]Settings[/b] — ↑/↓ select, Enter to change. * = restart required. Saved to settings.env.",
    "config.readonly_header": "[dim]Read-only (edit in settings.env; restart required):[/dim]",
    "restart.marker": " *",
    "val.on": "On",
    "val.off": "Off",
    "val.default": "(default)",
    "status.auth": "([b]{name}[/b]) Auth: [{color}]{state}[/{color}]",
    "status.auth_message": " [dim]({message})[/dim]",
    "extra.cookie_none": " | Cookies not set.",
    "extra.cookie_live": " | Cookies: {mm:02d}:{ss:02d} until expiry (TTL {ttl}m)",
    "extra.cookie_expired": " | Cookie likely expired. Refresh the cookie",
    "extra.ugoira": " | Ugoira: {mode}",
    "extra.twitter": " | yt-dlp: {fmt}",
    "dl.queue_idle": "Queue: -",
    "dl.ready": "Ready to download",
    "dl.overall": "Downloaded: {done} files · {mb:.1f} MB",
    "dl.file_progress": "{filename}  {done:.1f}/{total:.1f} MB | {speed:.2f} MB/s",
    "dl.file_progress_nosize": "{filename}  {done:.1f} MB | {speed:.2f} MB/s",
    "dl.size_unknown": " size unknown",
    "log.debug_on": "[dim]DEBUG logging enabled.[/dim]",
    "log.auth_status": "[dim]Auth[/dim] {name}: {state} — {message}",
    "log.need_number": "[red]{label}: a number is required, got '{value}'[/red]",
    "log.save_failed": "[red]Failed to save settings.env: {error}[/red]",
    "log.apply_failed": "[yellow]{label}: saved, but not applied: {error}[/yellow]",
    "log.restart_hint": " [dim](reboot to apply)[/dim]",
    "log.setting_saved": "[green]{label} → {value}[/green]{hint}",
    "log.checking_auth": "[dim]Checking auth...[/dim]",
    "log.reloaded_links": "[b]{name}[/b]: link buffer reloaded → {n} queued",
    "log.auth_busy": "[yellow]Download in progress — auth refresh unavailable.[/yellow]",
    "log.auth_no_refresh": "[yellow]{name}: interactive auth refresh is not supported ({message}).[/yellow]",
    "log.already_downloading": "[yellow]Download already in progress.[/yellow]",
    "log.start": "[b]Start[/b]: {name}",
    "log.download_done": "[green]Download complete.[/green]",
    "log.event_error": "[red]\\[{prefix}] {message}[/red]",
    "log.event_info": "[dim]\\[{prefix}][/dim] {message}",
    "log.checking_updates": "[dim]Checking lib updates...[/dim]",
    "log.pkg_error": "[red]{pkg}: {error}[/red]",
    "log.upgrade_busy": "[yellow]Upgrade already in progress...[/yellow]",
    "log.upgrade_start": "[yellow]Upgrading outdated packages...[/yellow]",
    "log.pkg_check_failed": "[red]{pkg}: check failed: {error}[/red]",
    "log.pkg_uptodate": "[green]{pkg}: already up to date ({installed})[/green]",
    "log.pkg_upgrading": "[yellow]{pkg}: upgrading {installed} → {latest}...[/yellow]",
    "log.pkg_pip_failed": "[red]{pkg}: pip failed to start: {error}[/red]",
    "log.pkg_done": "[green]{pkg}: done[/green] [dim]{tail}[/dim]",
    "log.pkg_pip_code": "[red]{pkg}: pip exit code {code}[/red] [dim]{tail}[/dim]",
    "log.all_uptodate": "[green]Everything is already up to date.[/green]",
    "log.restart_to_apply": "[dim]Restart to apply updates.[/dim]",
    "log.reboot_busy": "[yellow]Download in progress — wait for it to finish before restarting.[/yellow]",
    "event.auth_check_failed": "auth check failed: {error}",
    "event.auth_not_ready": "Auth not ready: {message}.",
    "auth.suspend_title": "  {name}: auth refresh",
    "auth.suspend_intro": "Follow the prompts below. The UI will return when finished.\n",
    "auth.suspend_result": "\nResult: {state}",
    "auth.suspend_error": "Auth refresh error: {error}",
    "auth.suspend_return": "\nPress Enter to return.",
    "prov.auth_not_required": "Auth is not required.",
    "prov.downloading": "Downloading: {filename}",
    "run.links_file": "Links file: {path}",
    "run.no_new": "No new links.",
    "run.new_count": "New links: {n}",
    "run.resolve_crash": "Provider crashed while resolving link: {error}",
    "run.resolve_failed": "Could not resolve {url}",
    "run.already_had": " (already downloaded)",
    "run.ok": "OK: {filename}{suffix}",
    "run.fail": "FAIL: {filename}: {error}",
    "danbooru.auth_no_creds": "Credentials are missing",
    "danbooru.auth_no_cookie": "Runtime Cloudflare cookie is missing",
    "danbooru.auth_ok": "",
    "danbooru.auth_failed": "Danbooru check failed: {error}",
    "danbooru.refresh_title": "\nDanbooru auth refresh",
    "danbooru.refresh_1": "1) Browser will open Danbooru.",
    "danbooru.refresh_2": "2) Pass Cloudflare/login if needed.",
    "danbooru.refresh_3": "3) Use Danbooru Cookie Helper extension -> Copy cookie.",
    "danbooru.refresh_4": "4) Paste cookie below. Cookie is kept in RAM for this run.\n",
    "danbooru.cookie_prompt": "Paste Danbooru Cookie header: ",
    "danbooru.cookie_missing": "Cookie was not provided",
    "danbooru.bad_url": "Could not extract id from Danbooru URL",
    "danbooru.api_error": "Danbooru API unavailable. Error: {error}",
    "danbooru.no_media": "Danbooru post {post_id}: media URL not found",
    "gelbooru.auth_missing": "Credentials are missing",
    "gelbooru.auth_ok": "",
    "gelbooru.bad_url": "Could not extract id from Gelbooru URL",
    "gelbooru.need_creds": "Gelbooru API requires credentials in settings.env",
    "gelbooru.api_error": "Gelbooru API unavailable or keys are invalid: {error}",
    "gelbooru.not_found": "Gelbooru post {post_id} not found",
    "gelbooru.no_media": "Gelbooru post {post_id}: media URL not found",
    "moebooru.auth_optional": "Auth is recommended, but not required",
    "moebooru.auth_ok": "",
    "moebooru.auth_incomplete": "Credentials are missing",
    "moebooru.bad_url": "Could not extract id from {name} URL",
    "moebooru.not_found": "{name} post {post_id} not found",
    "moebooru.no_media": "{name} post {post_id}: media URL not found",
    "sankaku.auth_ok": "",
    "sankaku.auth_missing": "Credentials or token are missing",
    "sankaku.auth_failed": "Sankaku auth check failed: {error}",
    "sankaku.bad_url": "Could not extract Sankaku post id",
    "sankaku.not_found": "Sankaku post {post_id} not found / API unavailable",
    "sankaku.no_media": "Sankaku post {post_id}: media URL not found",
    "pixiv.no_gppt": "gppt is not installed. Install it: pip install gppt",
    "pixiv.gppt_no_token": "gppt did not return a refresh_token",
    "pixiv.no_pixivpy": "pixivpy3 is not installed: pip install pixivpy3",
    "pixiv.empty_token": "Empty Pixiv refresh_token",
    "pixiv.auth_no_token": "Pixiv refresh_token is missing",
    "pixiv.auth_ok": "",
    "pixiv.auth_failed": "Pixiv token check failed: {error}",
    "pixiv.refresh_title": "\nPixiv auth refresh",
    "pixiv.refresh_intro": "A browser window will be opened by gppt. Log in to Pixiv there if asked.\n",
    "pixiv.gppt_login_failed": "Pixiv gppt login failed: {error}",
    "pixiv.token_missing_refresh": "Credentials are missing.",
    "pixiv.bad_url": "Could not extract Pixiv artwork id",
    "pixiv.not_found": "Pixiv artwork {illust_id} not found",
    "pixiv.no_media": "Pixiv artwork {illust_id}: media URL not found",
    "twitter.bad_url": "Could not extract tweet/status id",
    "twitter.no_ytdlp": "yt-dlp is not installed",
    "twitter.ytdlp_status": "Downloading via yt-dlp",
}


# All available languages. Add more by translating a copy of ``_RU``.
STRINGS: dict[str, dict[str, str]] = {
    "ru": _RU,
    "en": _EN,
}

def t(key: str, /, **kwargs: object) -> str:
    table = STRINGS.get(LANG) or _RU
    template = table.get(key)
    if template is None and table is not _RU:
        template = _RU.get(key)
    if template is None:
        return key
    if not kwargs:
        return template
    try:
        return template.format(**kwargs)
    except (KeyError, IndexError, ValueError):
        return template

def _detect_language(default: str = "ru") -> str:
    try:
        from .config import app_root, parse_env_file
        root = app_root()
        env_path = root / "settings.env"
        if not env_path.exists():
            env_path = root / "settings.env.example"
        values = parse_env_file(env_path)
        lang = (values.get("LANG") or "").strip().lower()
        if lang in STRINGS:
            return lang
    except Exception:
        pass
    return default

LANG = _detect_language(LANG)